### ISSUE TITLE
Ajout du code ?

### ISSUE THREAD

**Issue by redianthus** [Geekin-side/LLDC#5]
Salutations,

Nous sommes quelques joueurs à être intéressés par la mise à disposition du code au public [1], qui sait, on pourra peut-être aider... Voire même des specs si elles ont été rédigées.

@Ultim4T0m :)

[1] http://www.lldc.fr/membres/amneroth.php#!idSujet=3182_page=1

**Comment by laarmen** [comment]
Pour info, on va probablement garder ce dépot en simple miroir, et utiliser le dépot Gitlab actuel en principal.

**Comment by redianthus** [comment]
Yep' c'est ce qu'Ulti avait l'air de dire, pas de soucis !

**Comment by redianthus** [comment]
C'est réglé depuis un petit moment, je ferme !
